### ISSUE TITLE
PAF dont check slave status on master

### ISSUE THREAD

**Issue by ARogovsky** [dalibo/PAF#15] opened 2016-04-14 10:27 UTC
Hi. I have deep test PAF and find problem.
One my slave lost replication due by unexcepted shutdown. After start it write in log:
```
2016-04-14 10:42:21 MSK LOG:  started streaming WAL from primary at 37B/75000000 on timeline 12
2016-04-14 10:42:21 MSK FATAL:  could not receive data from WAL stream: ERROR:  requested starting point 37B/75000000 is ahead of the WAL flush position of this server 37B/7408C5F8
	
2016-04-14 10:42:21 MSK LOG:  received fast shutdown request
2016-04-14 10:42:21 MSK LOG:  aborting any active transactions
2016-04-14 10:42:21 MSK FATAL:  terminating connection due to administrator command
2016-04-14 10:42:21 MSK LOG:  shutting down
2016-04-14 10:42:21 MSK LOG:  database system is shut down

pg_lsclusters who db is online, but in fact db is down.
```

Checking query for master like SELECT client_addr,sync_state from pg_stat_replication confirm replication lost.I belive, this status may receive via slave/status code or other thing. 
Your RAF should checking status and down failed slaves db.

**Comment by ioguix** [comment] 2016-04-14 10:37
Hi,

If I understand correctly your concern, actually yes, our RA is checking the slaves status. See:
https://github.com/dalibo/PAF/blob/master/script/pgsqlms#L377

At each monitor action on the master, it checks the situation of all the slaves connected to it by querying its pg_stat_replication local table. Any node which does not appear in the table will have a master score set to 0 and a warning is issued in the log file, see: https://github.com/dalibo/PAF/blob/master/script/pgsqlms#L507

**Comment by ARogovsky** [comment] 2016-04-14 11:24
So, I was have problem when failed resource stay alive. I will down it via pg_ctlcluster and cleanup ms. After this node marked as dow.

Let me explain problem deeper:
Slave node is miss timeline/wal log from master and go to infinity trying replication:
cp: cannot stat ‘/var/lib/postgresql/9.4/pg_archive/0000000D.history’: No such file or directory
cp: cannot stat ‘/var/lib/postgresql/9.4/pg_archive/0000000C0000037B00000075’: No such file or directory
2016-04-14 14:19:16 MSK LOG:  started streaming WAL from primary at 37B/75000000 on timeline 12
2016-04-14 14:19:16 MSK FATAL:  could not receive data from WAL stream: ERROR:  requested starting point 37B/75000000 is ahead of the WAL flush position of this server 37B/74094A10

This attempts will not finished.

I was configured this node as primary and demote/promote. Now ms cant define master, becouse waiting when this node becomes to master, but this is newer be.

Usually I set "op monitor interval=30s on-fail=restart role=Master timeout=160s" for this issue.

How you resolve this problem?

**Comment by ARogovsky** [comment] 2016-04-14 11:32
Also question, when you change master - did you doing promote on new? I meant command **pg_ctl promote**.
This is very important.

**Comment by ioguix** [comment] 2016-04-14 12:48
I'm not sure I understand your situation here.

But anyway, you must __not__ control your PostgreSQL instances by hands using `pg_ctl` or `pg_ctlcluster` or anything else. The only way to interact with your PostgreSQL instances is through the cluster resource manager, using `crm_resource` or `crmsh` (or `pcs` on RHEL-like OS).

If you start/stop/promote/whatever your instance without asking the Resource Manager to do it for you, expect it to react badly, unless you put the cluster in `maintenance-mode` first.

We did a lot of tests with our RA (`pgsqlms`, __NOT__ the official one `pgsql`) and I can confirm you we did __a lot__ of switchover between the master and a slave with success using `crm_resource --move --master [...]` (or `pcs resource move`). Maybe the `crm` command supports to move the master role (the manpage is not clear enough), but if not, rely on `crm_resource` which is provided with pacemaker on your system.

**Comment by ioguix** [comment] 2016-04-14 12:50
And yes, obviously, the resource agent is doing a `pg_ctl promote` to promote a slave as master. See: https://github.com/dalibo/PAF/blob/master/script/pgsqlms#L1404

**Comment by ARogovsky** [comment] 2016-04-14 14:29
Thanks. I thinking problem in my config, becouse I was enabled wal_archive. This is not working with pg_ctl promote.
But it need me for increment backups.
I will checking deeper.

**Comment by ioguix** [comment] 2016-04-14 14:36
`wal_archive`? what are you talking about? `wal_level = archive` maybe ? 

Moreover, I don't get the point between `pg_ctl promote` and  wal archiving...(you can `pg_ctl promote` a warm standby in PostgreSQL). 

This is very confusing.

And remember, you should __NOT__ do a `pg_ctl promote` yourself. Thc cluster manager should perform it for you to keep track of everything!

**Comment by ARogovsky** [comment] 2016-04-14 14:58
This describled here:
http://michael.otacoo.com/postgresql-2/postgres-9-3-feature-highlight-timeline-switch-of-slave-node-without-archives/

**Comment by ioguix** [comment] 2016-04-14 15:11
We know about this feature. But what is the point?

You can set up streaming replication and WAL archiving in the same time, I don't understand what is your problem. Even more concerning the promotion stuff.

Maybe you should start from scratch following our [Quick Start for Debian 8 documentation](http://dalibo.github.io/PAF/Quick_Start-Debian-8.html), test what you need in this context, then adapt the setup to suit your needs? Adding PITR backup on top of this is trivial and should not break your cluster.

**Comment by ARogovsky** [comment] 2016-04-14 15:23
Let me explain problem:
Server a is prefer master.
Server a is lost and master become to server b.
Server a is back, but unclean.
When I try cleanup ms pgsql resource, it try set srever a as masetr.
Server a can't stay masetr due by timeline & wall.

**Comment by ioguix** [comment] 2016-04-14 15:34
OK, so you had a failover. This is normal it can not catch the replication with server b. Should a failover occurs, you must rebuild your old master as a slave, then do a switchover if needed.

**Comment by ARogovsky** [comment] 2016-04-14 15:40
Yes. But when I cleanup ms resource - cluster try to set server a as master.
But server cant be master and goes to infinitry recovery.

**Comment by mrimbault** [comment] 2016-04-14 16:06
Hi,

You should not cleanup anything after a failover before the failed PostgreSQL instance has been manually and properly rebuilt.
I assume from our discussion on the previous issue (#14) that your cluster has an unreliable network between nodes `a` and `b`, and no fencing method available.
That would explain what you encounter (please correct me if I'm wrong):
  1. node `a` runs the master resource
  2. the cluster lose communication with node `a` long enough to mark it as `offline` or `unclean`
  3. so the PostgreSQL resource on node `b` is promoted instead
  4. but as you disabled fencing, node `a` is still running, and comes back still alive and kicking (hopefully the resource was stopped on node `a` due to the quorum lost at this point, and thus marked it as `failed` or `stopped` - if not, then you have a split brain situation)
  5. then you do a manual cleanup of the PostgreSQL resource __without rebuilding the PostgreSQL instance from the new primary__

First, step 4. should not be allowed to happen.
As already mentioned, fencing is a mandatory element of any high availability configuration, without it your cluster will fail in a spectacular way, eventually (see also http://dalibo.github.io/PAF/fencing.html).

Then, at step 5., once another PostgreSQL has been promoted, your old PostgreSQL primary instance can not be "demoted", meaning it can not be re-started as a slave and join the replication with node `b`.
At this point, both Pacemaker and PostgreSQL should be stopped on node `a` (due to fencing), and __you have to rebuild your old primary instance from the new one running on node `b`__ (for instance, using `pg_basebackup` tool, or another method, as seems fit to your configuration).

Only once this rebuilt is done will the PostgreSQL instance on node `a` be able to join the cluster again. At this point, you can finally start Pacemaker and cleanup the failcount.

But that's not the main concern here, the lack of a fencing device and the unreliable network is something you should address first.

**Comment by ARogovsky** [comment] 2016-04-15 04:11
Thanks for explain. I will not use clean.

**Comment by mrimbault** [comment] 2016-04-15 07:22
Well, you _can_ cleanup the resource, but __only__ if it is actually "clean" (meaning, the PostgreSQL instance has been rebuilt after the failover).

I'll close this issue.

**Closed by mrimbault** 2016-04-15 07:22 UTC
